language: java
jdk:
  - oraclejdk8
before_install:
 - chmod +x gradlew
script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
    - ./gradlew test
