import com.google.common.util.concurrent.Futures;
import com.google.common.util.concurrent.ListenableFuture;
import lombok.extern.slf4j.Slf4j;

import java.util.concurrent.ExecutionException;
import java.util.concurrent.Executor;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'saramakm' at '9/5/15 3:46 PM' with Gradle 2.6
 *
 * @author saramakm, @date 9/5/15 3:46 PM
 */
@Slf4j
public class Main {

    public static void main(String[] args) {
        log.info("See tests :) ");
    }

}
